-- ============================================================
--    suppression des donnees
-- ============================================================

delete from CLUB ;
delete from PERSONNE ;
delete from EQUIPE ;
delete from CATEGORIE ;
delete from ENTRAINE ;
delete from JOUEUR ;
delete from PARTICIPE ;
delete from RENCONTRE ;
delete from ENTRAINEUR ;

commit ;

-- ============================================================
--    creation des donnees
-- ============================================================

-- ENTRAINEUR

insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values (  'MONTAND'   , 'YVES'        , '13-OCT-61' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values (  'GARCIA'    , 'NICOLE'      , '21-FEB-67' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'VILLERET'  , 'JACQUES'     , '06-FEB-71' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'DUBOIS'    , 'MARIE'       , '12-FEB-67' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'SCHNEIDER' , 'ROMY'        , '01-APR-62' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'FREY'      , 'SAMY'        , '24-MAY-70' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'RICARDO'   , 'BRUNOZZI'    , '08-APR-68' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'DUPRILLOT' , 'JOHEL'       , '24-APR-78' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values (  'LESTRADOS' , 'DOMINIQUOS'  , '19-FEB-79' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'DELON'     , 'ALAIN'       , '04-OCT-73' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'VENTURA'   , 'LINO'        , '01-JAN-71' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values (  'MASSARI'   , 'LEA'         , '01-MAR-71' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'POIRET'    , 'JEAN'        , '25-JAN-69' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'CLUZET'    , 'FRANCOIS'    , '01-NOV-74' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'MALAVOY'   , 'CHRISTOPHE'  , '01-MAY-78' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values (  'BOURVIL'   , 'BOURVIL'     , '11-APR-68' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'ROBERT'    , 'YVES'        , '06-JUL-68' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'MANESSE'   , 'GASPARD'     , '28-JUN-78' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'BELLI'     , 'AGOSTINA'    , '01-MAR-70' ) ;
insert into ENTRAINEUR(NOM_ENTRAINEUR, PRENOM_ENTRAINEUR, DATE_ENTREE_CLUB_ENTRAINEUR) values ( 'BRASSEUR'  , 'CLAUDE'      , '01-JAN-68' ) ;

commit;

-- CATEGORIES

insert into CATEGORIE (NOM_CATEGORIE) values ( 'BENJAMIN' );
insert into CATEGORIE (NOM_CATEGORIE) values ( 'CADET' );
insert into CATEGORIE (NOM_CATEGORIE) values( 'JUNIOR' );

commit;

-- CLUB

insert into CLUB ( NOM_CLUB) values ( 'ESPERANCE'     ) ;
insert into CLUB ( NOM_CLUB)  values ( 'AIGLES'   ) ;
insert into CLUB ( NOM_CLUB)  values ( 'PANTHERE'       ) ;
insert into CLUB ( NOM_CLUB)  values ( 'ETOILE'    ) ;
insert into CLUB  ( NOM_CLUB) values ( 'FALCON' ) ;
insert into CLUB  ( NOM_CLUB) values ( 'DRAGON'     ) ;
insert into CLUB  ( NOM_CLUB) values ( 'PAIX'      ) ;
insert into CLUB  ( NOM_CLUB) values ( 'LEOPARD'     ) ;
insert into CLUB  ( NOM_CLUB) values ( 'SUNSHINE'  ) ;
insert into CLUB  ( NOM_CLUB) values ( 'PHENIX'    ) ;

commit;

-- EQUIPE

insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'FC'   , 10 , 1 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values ( 'INTER'  , 9  , 2 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'US'    , 8  , 3 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'AS'  , 7  , 1 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'SCORPION'   , 6  , 2 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE)  values (  'FCA'     , 5  , 3 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'SPORTIF'  , 4  , 1 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'ATLETICO'   , 3  , 2 ) ;
insert into EQUIPE( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE)  values (  'ASC'      , 2  , 3 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE)  values (  'FCM'  , 1  , 1 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE)  values (  'CAB'      , 10 , 2 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'EST'    , 9  , 3 ) ;
insert into EQUIPE( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE)  values (  'CA'     , 8  , 1 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'ASG'   , 7  , 2 ) ;
insert into EQUIPE ( NOM_EQUIPE, NUMERO_CLUB, NUMERO_CATEGORIE) values (  'FCB'   , 6  , 3 ) ;

commit;

-- ENTRAINE

insert into ENTRAINE values (1 ,  1 ) ;
insert into ENTRAINE values (2 ,  2 ) ;
insert into ENTRAINE values (3 ,  3 ) ;
insert into ENTRAINE values (  4 ,  4 ) ;
insert into ENTRAINE values (  5 ,  5 ) ;
insert into ENTRAINE values (  6 ,  6 ) ;
insert into ENTRAINE values (  7 ,  7 ) ;
insert into ENTRAINE values (  8 ,  8 ) ;
insert into ENTRAINE values (  9 ,  9 ) ;
insert into ENTRAINE values ( 10 ,  10 ) ;
insert into ENTRAINE values ( 11 ,  11 ) ;
insert into ENTRAINE values ( 12 ,  12 ) ;
insert into ENTRAINE values ( 13 ,  13 ) ;
insert into ENTRAINE values ( 14 ,  14 ) ;
insert into ENTRAINE values ( 15 ,  15 ) ;
commit;

-- RENCONTRE

insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values (   '13-OCT-12' , 11 , 33 , 1  , 2 ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values (  '21-FEB-12' , 20 , 26 , 3  , 4 ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values (  '06-FEB-11' , 23 , 33 , 5  , 6 ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values (  '12-FEB-11' , 22 , 25 , 7  , 8 ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values (  '01-APR-12' , 33 , 22 , 9  , 10) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values (  '24-MAY-10' , 34 , 22 , 11 , 12 ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values (  '08-APR-08' , 30 , 25 , 13 , 14 ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values (  '24-APR-08' , 34 , 22 , 15 , 1  ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values (  '19-FEB-09' , 28 , 22 , 12 , 13 ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values ( '04-OCT-12' , 35 , 24 , 5  , 8  ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values ( '01-JAN-11' , 35 , 19 , 9  , 3  ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '01-MAR-11' , 32 , 23 , 2  , 10 ) ;
insert into RENCONTRE (DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2)values ( '25-JAN-08' , 25 , 32 , 4  , 7  ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '01-NOV-08' , 28 , 34 , 7  , 11 ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '01-MAY-09' , 25 , 33 , 5  , 8  ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '11-APR-09' , 24 , 18 , 6  , 9  ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '06-JUL-08' , 26 , 33 , 14 , 3  ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '28-JUN-08' , 34 , 22 , 15 , 2  ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '01-MAR-10' , 33 , 22 , 14 , 7  ) ;
insert into RENCONTRE(DATE_RENCONTRE, SCORE_EQUIPE1_RENCONTRE, SCORE_EQUIPE2_RENCONTRE, NUMERO_EQUIPE1, NUMERO_EQUIPE2) values ( '01-JAN-06' , 34 , 20 , 6  , 7  ) ;

commit ;

-- -- JOUEUR

insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'MONTAND'   , 'YVES'        , '13-OCT-81' , 'TALENCE'  , '14-JAN-01' , 1 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'GARCIA'    , 'NICOLAS'      , '21-FEB-87' , 'BORDEAUX' , '12-MAR-04' , 2 ) ;
insert into JOUEUR  (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE)values (  'VILLERET'  , 'JACQUES'     , '06-FEB-91' , 'BORDEAUX' , '06-JAN-99' , 3 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'DUBOIS'    , 'JEAN'       , '12-FEB-87' , 'BORDEAUX' , '16-OCT-06' , 4 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'SCHNEIDER' , 'ROMAIN'        , '01-APR-82' , 'PESSAC'   , '12-NOV-07' , 5 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'FREY'      , 'SAMY'        , '24-MAY-90' , 'PESSAC'   , '23-DEC-08' , 6 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'RICARDO'   , 'BRUNOZZI'    , '08-APR-88' , 'PESSAC'   , '15-SEP-03' , 7 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'DUPRILLOT' , 'JOEL'       , '24-APR-88' , 'PESSAC'   , '12-JAN-01' , 8 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'LESTRADOS' , 'DOMINIQUOS'  , '19-FEB-89' , 'BORDEAUX' , '27-JUL-02' , 9 ) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'DELON'     , 'ALAIN'       , '04-OCT-83' , 'TALENCE'  , '11-SEP-01' , 10) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'VENTURA'   , 'LINO'        , '01-JAN-91' , 'TALENCE'  , '12-JAN-05' , 11) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'MASSARI'   , 'LEO'         , '01-MAR-91' , 'TALENCE'  , '16-MAR-05' , 12) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'POIRET'    , 'JEAN'        , '25-JAN-89' , 'TALENCE'  , '19-OCT-04' , 13) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'CLUZET'    , 'FRANCOIS'    , '01-NOV-84' , 'TAELNCE'  , '16-NOV-03' , 14) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'MALAVOY'   , 'CHRISTOPHE'  , '01-MAY-88' , 'TALENCE'  , '13-DEC-08' , 15) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'BOURVIL'   , 'BOURVIL'     , '11-APR-88' , 'BORDEAUX' , '07-APR-05' , 11) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'ROBERT'    , 'YVES'        , '06-JUL-88' , 'BORDEAUX' , '03-NOV-04' , 14) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'MANESSE'   , 'GASPARD'     , '28-JUN-88' , 'BORDEAUX' , '08-JUN-03' , 13) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'BELLI'     , 'ANTHONY'    , '01-MAR-90' , 'PARIS'    , '17-MAY-06' , 1 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'BRASSEUR'  , 'CLAUDE'      , '01-JAN-88' , 'PARIS'    , '16-NOV-04' , 2 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'PONTEAU'   , 'NATHAN'        , '13-OCT-81' , 'TALENCE'  , '14-JAN-01' , 1 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'STALOS'    , 'NICOLAS'      , '21-FEB-87' , 'BORDEAUX' , '12-MAR-04' , 2 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE)  values (  'RHODES'    , 'THOMAS'     , '06-FEB-91' , 'BORDEAUX' , '06-JAN-99' , 3 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'BORNAT'    , 'JOFFREY'       , '12-FEB-87' , 'BORDEAUX' , '16-OCT-06' , 4 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'MAKARIOS'  , 'BASTIEN'        , '01-APR-82' , 'PESSAC'   , '12-NOV-07' , 5 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'HOMER'     , 'ARNAUD'        , '24-MAY-90' , 'PESSAC'   , '23-DEC-08' , 6 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'HALL'      , 'FRANCK'    , '08-APR-88' , 'PESSAC'   , '15-SEP-03' , 7 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'DORIAN'    , 'JEROME'       , '24-APR-88' , 'PESSAC'   , '12-JAN-01' , 8 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'LENOUVEAU' , 'ANTOINE'  , '19-FEB-89' , 'BORDEAUX' , '27-JUL-02' , 9 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'DEBON'     , 'PIERRE'       , '04-OCT-83' , 'TALENCE'  , '11-SEP-01' , 10) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'ADONIS'    , 'REMY'        , '01-JAN-91' , 'TALENCE'  , '12-JAN-05' , 11) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ('MONTAIGNE' , 'LEONARD'         , '01-MAR-91' , 'TALENCE'  , '16-MAR-05' , 12) ;
insert into JOUEUR (NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE)values (  'POULET'    , 'GOERGES'        , '25-JAN-89' , 'TALENCE'  , '19-OCT-04' , 13) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'CELERIER'  , 'NICOLAS'    , '01-NOV-84' , 'TAELNCE'  , '16-NOV-03' , 14) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'LEBLANC'   , 'FLORENT'  , '01-MAY-88' , 'TALENCE'  , '13-DEC-08' , 15) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'BLONEAU'   , 'FLORIAN'     , '11-APR-88' , 'BORDEAUX' , '07-APR-05' , 11) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'HOFER'     , 'BENJAMIN'        , '06-JUL-88' , 'BORDEAUX' , '03-NOV-04' , 14) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'PAGNY'     , 'SEBASTIEN'     , '28-JUN-88' , 'BORDEAUX' , '08-JUN-03' , 13) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values ( 'MASUN'     , 'ANTONIO'    , '01-MAR-90' , 'PARIS'    , '17-MAY-06' , 1 ) ;
insert into JOUEUR(NOM_JOUEUR, PRENOM_JOUEUR, DATE_de_NAISSANCE_JOUEUR, ADRESSE_JOUEUR, DATE_ENTREE_CLUB_JOUEUR, NUMERO_EQUIPE) values (  'CORENTIN'  , 'DAVID'      , '01-JAN-88' , 'PARIS'    , '16-NOV-04' , 2 ) ;

commit ;

-- PARTICIPE

insert into PARTICIPE values (  1 ,  1   ,0  , 1) ;
insert into PARTICIPE values (  1 ,  2   ,0  , 2) ;
insert into PARTICIPE values (  1 ,  3   ,5  , 3) ;
insert into PARTICIPE values (  1 ,  4   ,6  , 2) ;
insert into PARTICIPE values (  2 ,  2   ,2  , 2) ;
insert into PARTICIPE values (  2 ,  5   ,0  , 5) ;
insert into PARTICIPE values (  2 ,  6   ,3  , 0) ;
insert into PARTICIPE values (  2 ,  17  ,4  , 1) ;
insert into PARTICIPE values (  2 ,  10  ,3  , 1) ;
insert into PARTICIPE values (  2 ,  3   ,6  , 3) ;
insert into PARTICIPE values (  3 ,  1   ,5  , 1) ;
insert into PARTICIPE values (  3 ,  4   ,3  , 2) ;
insert into PARTICIPE values (  3 ,  15  ,5  , 1) ;
insert into PARTICIPE values (  3 ,  16  ,0  , 1) ;
insert into PARTICIPE values (  4 ,  17  ,4  , 1) ;
insert into PARTICIPE values (  4 ,  18  ,4  , 1) ;
insert into PARTICIPE values (  4 ,  1   ,1  , 0) ;
insert into PARTICIPE values (  4 ,  2   ,0  , 2) ;
insert into PARTICIPE values (  5 ,  3   ,5  , 3) ;
insert into PARTICIPE values (  5 ,  4   ,4  , 1) ;
insert into PARTICIPE values (  5 ,  2   ,5  , 2) ;
insert into PARTICIPE values (  5 ,  1   ,5  , 1) ;
insert into PARTICIPE values (  6 ,  10  ,4  , 1) ;
insert into PARTICIPE values (  6 ,  9   ,2  , 0) ;
insert into PARTICIPE values (  7 ,  7   ,1  , 2) ;
insert into PARTICIPE values (  7 ,  13  ,0  , 1) ;
insert into PARTICIPE values (  8 ,  12  ,1  , 1) ;
insert into PARTICIPE values (  8 ,  11  ,3  , 1) ;
insert into PARTICIPE values (  9 ,  19  ,2  , 1) ;
insert into PARTICIPE values (  9 ,  20  ,5  , 2) ;
insert into PARTICIPE values ( 10 ,  20  ,3  , 2) ;
insert into PARTICIPE values ( 10 ,  2   ,6  , 2) ;
insert into PARTICIPE values ( 11 ,  2   ,0  , 2) ;
insert into PARTICIPE values ( 11 ,  12  ,4  , 1) ;
insert into PARTICIPE values ( 11 ,  13  ,3  , 1) ;
insert into PARTICIPE values ( 11 ,  15  ,3  , 2) ;
insert into PARTICIPE values ( 12 ,  19  ,3 , 0) ;
insert into PARTICIPE values ( 12 ,  11  ,4 , 1) ;
insert into PARTICIPE values ( 12 ,  12  ,5 , 2) ;
insert into PARTICIPE values ( 13 ,  13  ,5 , 0) ;
insert into PARTICIPE values ( 13 ,  11  ,5 , 0) ;
insert into PARTICIPE values ( 13 ,  7   ,1 , 0) ;
insert into PARTICIPE values ( 13 ,  6   ,2 , 0) ;
insert into PARTICIPE values ( 13 ,  5   ,3 , 0) ;
insert into PARTICIPE values ( 13 ,  1   ,1 , 0) ;
insert into PARTICIPE values ( 14 ,  2   ,2 , 2) ;
insert into PARTICIPE values ( 14 ,  14  ,3 , 2) ;
insert into PARTICIPE values ( 14 ,  8   ,5 , 2) ;
insert into PARTICIPE values ( 14 ,  16  ,3 , 2) ;
insert into PARTICIPE values ( 15 ,  17  ,0 , 1) ;
insert into PARTICIPE values ( 15 ,  18  ,1 , 0) ;
insert into PARTICIPE values ( 15 ,  15  ,4 , 3) ;
insert into PARTICIPE values ( 16 ,  16  ,0 , 1) ;
insert into PARTICIPE values ( 16 ,  17  ,3 , 2) ;
insert into PARTICIPE values ( 17 ,  18  ,2 , 0) ;
insert into PARTICIPE values ( 17 ,  17  ,1 , 1) ;
insert into PARTICIPE values ( 17 ,  19  ,4 , 1) ;
insert into PARTICIPE values ( 17 ,  14  ,4 , 0) ;
insert into PARTICIPE values ( 18 ,  13  ,4 , 2) ;
insert into PARTICIPE values ( 18 ,  15  ,3 , 0) ;
insert into PARTICIPE values ( 18 ,  5   ,4 , 2) ;
insert into PARTICIPE values ( 18 ,  6   ,5 , 1) ;
insert into PARTICIPE values ( 18 ,  7   ,2 , 1) ;
insert into PARTICIPE values ( 18 ,  8   ,3 , 0) ;
insert into PARTICIPE values ( 18 ,  18  ,3 , 2) ;
insert into PARTICIPE values ( 19 ,  19  ,2 , 0) ;
insert into PARTICIPE values ( 19 ,  9   ,2 , 1) ;
insert into PARTICIPE values ( 19 ,  10  ,0 , 3) ;
insert into PARTICIPE values ( 19 ,  11  ,1 , 2) ;
insert into PARTICIPE values ( 20 ,  2   ,0 , 1) ;
insert into PARTICIPE values ( 20 ,  20  ,1 , 0) ;
insert into PARTICIPE values ( 20 ,  8   ,1 , 2) ;
insert into PARTICIPE values ( 20 ,  7   ,2 , 0) ;
insert into PARTICIPE values ( 20 ,  6   ,0 , 0) ;
insert into PARTICIPE values ( 20 ,  9   ,2 , 1) ;

commit;

-- PERSONNE

insert into PERSONNE (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'MALLE' ,'ROBAT', 'TALENCE' , 'PRESIDENT', 1);
insert into PERSONNE (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'PONTUS','RAPHAEL', 'TALENCE' , 'VICE-PRESIDENT', 1);
insert into PERSONNE (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'MOLLAT' ,'JEAN', 'TALENCE' , 'TRESORIER',     1);
insert into PERSONNE  (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB)values ( 'MOUTON' ,'PIERRE', 'TALENCE' , 'SECRETAIRE',  1);
insert into PERSONNE  (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB)values ( 'POIREAU' ,'FLORENT', 'TALENCE' , 'PRESIDENT',      2);
insert into PERSONNE (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'LEVEQUE' ,'FLORIAN', 'TALENCE' , 'VICE-PRESIDENT', 2);
insert into PERSONNE (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'SYLVAIN' ,'NATHAN', 'TALENCE' , 'TRESORIER',     2);
insert into PERSONNE (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'STEPHANE' ,'NICOLAS', 'TALENCE' , 'SECRETAIRE',  2);
insert into PERSONNE (NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'GUILLEREZ' ,'JAMES', 'TALENCE' , 'PRESIDENT',      3);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'GOMEZ' ,'JOFFREY', 'TALENCE' , 'VICE-PRESIDENT', 3);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'HERNANDEZ' ,'BASTIEN', 'TALENCE' , 'TRESORIER',     3);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'FERNANDEZ' ,'JEREMY', 'TALENCE' , 'SECRETAIRE',  3);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'MOURET' ,'JEAN', 'TALENCE' , 'PRESIDENT',      4);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'DELON' ,'NICOLAS', 'TALENCE' , 'VICE-PRESIDENT', 4);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'MARTIN' ,'PIERRE', 'TALENCE' , 'TRESORIER',     4);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'SELLAM' ,'QUENTIN', 'TALENCE' , 'SECRETAIRE',  4);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'MORIZET' ,'ANTOINE', 'TALENCE' , 'PRESIDENT',      5);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'DEBON' ,'ERWAN', 'TALENCE' , 'VICE-PRESIDENT', 5);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'LEBON' ,'BEN', 'TALENCE' , 'TRESORIER',     5);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'DUBOIS' ,'OLIVIER', 'TALENCE' , 'SECRETAIRE',  5);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'BENOIT' ,'DENIS', 'TALENCE' , 'PRESIDENT',      6);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'RUELLE' ,'FRANCOIS', 'TALENCE' , 'VICE-PRESIDENT', 6);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'SANTOS' ,'JULIEN', 'TALENCE' , 'TRESORIER',     6);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'BLANCO' ,'RAPHAEL', 'TALENCE' , 'SECRETAIRE',  6);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'LEBLANC' ,'EMMANUEL', 'TALENCE' , 'PRESIDENT',      7);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'RASTRERO' ,'EDDY', 'TALENCE' , 'VICE-PRESIDENT', 7);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'NAVAS' ,'DANIEL', 'TALENCE' , 'TRESORIER',     7);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'BIENVENU' ,'DANNY', 'TALENCE' , 'SECRETAIRE',  7);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'DUBERNET' ,'SIMON', 'TALENCE' , 'PRESIDENT',      8);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'COLAF' ,'THOMAS', 'TALENCE' , 'VICE-PRESIDENT', 8);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'GABIN' ,'JULIEN', 'TALENCE' , 'TRESORIER',     8);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'POQUET' ,'FRED', 'TALENCE' , 'SECRETAIRE',  8);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'LECLERC' ,'PHILIPPE', 'TALENCE' , 'PRESIDENT',      9);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'FONTIN' ,'JEAN', 'TALENCE' , 'VICE-PRESIDENT', 9);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'MEUNIER' ,'ROBAT', 'TALENCE' , 'TRESORIER',     9);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'HENRI' ,'NICOLAS', 'TALENCE' , 'SECRETAIRE',  9);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'GALERON' ,'HERVE', 'TALENCE' , 'PRESIDENT',      10);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'RENARD' ,'JOHN', 'TALENCE' , 'VICE-PRESIDENT', 10);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'DUSSAUT' ,'PATRICK', 'TALENCE' , 'TRESORIER',     10);
insert into PERSONNE(NOM_PERSONNE, PRENOM_PERSONNE, ADRESSE_PERSONNE, FONCTION_PERSONNE, NUMERO_CLUB) values ( 'LEMAIRE' ,'ARNAUD', 'TALENCE' , 'SECRETAIRE',  10);

commit;

-- -- ============================================================
-- --    verification des donnees
-- -- ============================================================

select count(*),'= 20 ?','ENTRAINEUR' from ENTRAINEUR 
union
select count(*),'= 3 ?','CATEGORIE' from CATEGORIE 
union
select count(*),'= 10 ?','CLUB' from CLUB 
union
select count(*),'= 15 ?','EQUIPE' from EQUIPE
union
select count(*),'= 20 ?','ENTRAINE' from ENTRAINE 
union
select count(*),'= 20 ?','RENCONTRE' from RENCONTRE 
union
select count(*),'= 40 ?','JOUEUR' from JOUEUR 
union
select count(*), '=75 ?','PARTICIPE' from PARTICIPE
union
select count(*),'= 40 ?','PERSONNE' from BUREAU ;
