-- La feuille du match à une date donnée --
-- Input : date --
-- Exemple date : 21-feb-87 --

(select distinct NOM_EQUIPE as EQUIPE , SCORE_EQUIPE1_RENCONTRE as SCORE_EQUIPE , NOM_JOUEUR as JOUEURS from EQUIPE E, RENCONTRE R, PARTICIPE P, JOUEUR J where E.NUMERO_EQUIPE = R.NUMERO_EQUIPE1 and R.NUMERO_RENCONTRE = P.NUMERO_RENCONTRE and P.NUMERO_LICENCE = J.NUMERO_LICENCE and R.DATE_RENCONTRE = '21-feb-12' )
union
(select distinct NOM_EQUIPE as EQUIPE , SCORE_EQUIPE2_RENCONTRE as SCORE_EQUIPE , NOM_JOUEUR as JOUEURS from EQUIPE E, RENCONTRE R, PARTICIPE P, JOUEUR J where E.NUMERO_EQUIPE = R.NUMERO_EQUIPE2 and R.NUMERO_RENCONTRE = P.NUMERO_RENCONTRE and P.NUMERO_LICENCE = J.NUMERO_LICENCE and R.DATE_RENCONTRE = '21-feb-12');